/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panels;

import View.StaticBackground;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author yatac
 */
public class PanelCalculate extends javax.swing.JPanel {

    /**
     * Creates new form Calculate
     */
    public PanelCalculate() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new StaticBackground.FondoPanelTxt();
        jPanel2 = new StaticBackground.FondoPanelTxt();
        ButtonCalculate = new javax.swing.JLabel();
        ButtonAddData = new javax.swing.JLabel();
        ButtonAddFile = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12", "23"},
                {"123", "323"},
                {"12", "12"},
                {"123", "123"},
                {"32", null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        ButtonCalculate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonCalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/ButtonCalculate.png"))); // NOI18N
        ButtonCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCalculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCalculateMouseExited(evt);
            }
        });

        ButtonAddData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonAddData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/ButtonAddData.png"))); // NOI18N
        ButtonAddData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAddDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAddDataMouseExited(evt);
            }
        });

        ButtonAddFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonAddFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/ButtonAddFile.png"))); // NOI18N
        ButtonAddFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAddFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAddFileMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/Y.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/X.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(ButtonAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(ButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddDataMouseEntered
       ButtonAddData.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonAddDataoOpaque.png")));
       
    }//GEN-LAST:event_ButtonAddDataMouseEntered

    private void ButtonAddDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddDataMouseExited
       ButtonAddData.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonAddData.png")));
    }//GEN-LAST:event_ButtonAddDataMouseExited

    private void ButtonAddFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddFileMouseClicked

    private void ButtonAddDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddDataMouseClicked

    private void ButtonAddFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddFileMouseEntered
        ButtonAddFile.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonAddFileOpaque.png")));
    }//GEN-LAST:event_ButtonAddFileMouseEntered

    private void ButtonAddFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddFileMouseExited
        ButtonAddFile.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonAddFile.png")));
    }//GEN-LAST:event_ButtonAddFileMouseExited

    private void ButtonCalculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCalculateMouseEntered
        ButtonCalculate.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonCalculateOpaque.png")));
    }//GEN-LAST:event_ButtonCalculateMouseEntered

    private void ButtonCalculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCalculateMouseExited
        ButtonCalculate.setIcon(new ImageIcon(getClass().getResource("/img/buttons/ButtonCalculate.png")));
    }//GEN-LAST:event_ButtonCalculateMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonAddData;
    private javax.swing.JLabel ButtonAddFile;
    private javax.swing.JLabel ButtonCalculate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
